server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: productos-service
          uri: lb://productos-service
          predicates:
            - Path=/productos/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/invoices/**

        - id: idau-service
          uri: http://localhost:8000
          predicates:
            - Path=/idau/**
          filters:
            - RewritePath=/idau/(?<segment>.*), /$\{segment}