server:
  port: 8001
  error:
    include-stacktrace: never

spring:
  sql:
    init:
      mode: always
      continue-on-error: true
  application:
    name: productos-service
  main:
    banner-mode: off
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Lima

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true
  jmx:
    enabled: false

#hikariCP
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: SpringBootHikariCP
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
      max-lifetime: 20000
    url: jdbc:postgresql://localhost:5434/service_productos
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    hystrix:
      stream:
        enabled: true
    web:
      exposure:
        include: "*"

# CURSO
# https://www.youtube.com/watch?v=p5uMy2DLE7A&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=7
# https://github.com/digitallab-academy/ms-course-youtube/tree/master/product-service
