server:
  port: 8003
  error:
    include-stacktrace: never

spring:
  sql:
    init:
      mode: always
      continue-on-error: true
  application:
    name: ws-shopping
  main:
    banner-mode: off
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Lima

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true
  jmx:
    enabled: false

#hikariCP
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    poolName: SpringBootHikariCP
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
      max-lifetime: 20000
    url: jdbc:postgresql://localhost:5434/service_shopping
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      import-check:
        enabled: false

# https://www.youtube.com/watch?v=P6vrSi6L3Gs&list=PLxy6jHplP3Hi_W8iuYSbAeeMfaTZt49PW&index=11